### ISSUE TITLE
import

### ISSUE THREAD

**Issue by gilyoktan** [OliverKohlDSc/Terminals#1]

**Comment by OliverKohlDSc** [comment]
@gilyoktan 

would you please be so kind to be a bit more concrete?
What do you mean?

Isn't it possible to open the solution in Visual Studio/Sharp Develop/... or do you have problems to import a third party file into the Terminals configuration?

Thanks
Oliver

**Comment by OliverKohlDSc** [comment]
Closed due to no response after a few months.
