### ISSUE TITLE
Hotkeys not working with 4.9.1.0

### ISSUE THREAD

**Issue by CarlKnox** [OliverKohlDSc/Terminals#21]
I use AutoHotKey.
4.9.0.0 worked fine with AHK. Specifically Ctrl-@ would enter my email address for IE and Firefox connections.
4.9.1.0 is preventing this from working. I didn't find any overrides in the Options menu.

**Comment by CarlKnox** [comment]
Now this is working.
I'll check again tomorrow if I get prompted for a new release to see if this might have prevented AHK from working.

**Comment by OliverKohlDSc** [comment]
@CarlKnox thanks a lot!
