### ISSUE TITLE
Check for new release on startup

### ISSUE THREAD

**Issue by CarlKnox** [OliverKohlDSc/Terminals#22]
4.9.0.0 had this issue and it persists with 4.9.1.0
My Terminals seems to find a new release each time I start. It will execute the upgrade which closes my current instance and launch again, then is doesn't find a new release until the next time I start Terminals. Knowing this hasn't found or installed newer releases, I pretty much ignore this. I can disable it in Options (I believe) but would like this to recognize that I am running the current release at startup.

**Comment by OliverKohlDSc** [comment]
@CarlKnox 
Has the problem been fixed for you?
https://github.com/OliverKohlDSc/Terminals/releases/tag/4.9.1.0
Thanks
Oliver
