### ISSUE TITLE
Unused and error prone toolbar icons

### ISSUE THREAD

**Issue by OliverKohlDSc** [OliverKohlDSc/Terminals#26]
Reported by @CarlKnox
Additionally, there is a toolbar button which isn’t descriptive and doesn’t appear to do anything. It’s the one which looks like a recycle icon, toolStripButtun4. Perhaps there’s something I don’t have installed, external to Terminals, which this opens.

**Comment by OliverKohlDSc** [comment]
@CarlKnow can you confirm that the error is gone?
Thanks
Oliver

**Comment by CarlKnox** [comment]
I’ll see if I can do this tonight. I’ll get to it tomorrow at the latest.

**Comment by OliverKohlDSc** [comment]
Dear @CarlKnox,

have you had the possibility to check if the problem is gone.

Thanks a lot!

Oliver

**Comment by CarlKnox** [comment]
Unfortunately, I was laid off today.

I’ll have to test once I find a new gig.

 

Carl Knox

**Comment by OliverKohlDSc** [comment]
Thanks
