### ISSUE TITLE
Terminals installer

### ISSUE THREAD

**Issue by CarlKnox** [OliverKohlDSc/Terminals#3]
I've downloaded the v4.7.3.0 binaries and don't find a setup or installer program. I also don't see documentation on how to perform the installation. I see the release notes for v4.7.0.0 state that an obsolete installer was removed. Perhaps this is fine for those with the application already installed, but where do people find the installer for new installations?

**Comment by OliverKohlDSc** [comment]
You are totally right. I'll build a installer package in the next few days.

**Comment by OliverKohlDSc** [comment]
You are totally right. I'll build an installer package in the next few days.

**Comment by CarlKnox** [comment]
Great! I’d love to try the software.

**Comment by OliverKohlDSc** [comment]
Please find below the link to the installer:

**Comment by OliverKohlDSc** [comment]
https://github.com/OliverKohlDSc/Terminals/releases/download/4.7.4.0/Setup_4.7.4.0.exe

**Comment by OliverKohlDSc** [comment]
Have you already had the chance to test the software?
Best regards
Oliver

**Comment by CarlKnox** [comment]
I was able to install yesterday afternoon and gave it a brief trial which seems to work.

 

There are a couple of quirky things to report.

*         I was running Rob Chartier’s Terminals prior and exported the favorites. This version does not import that file. Can I, perhaps, just copy those XML files into the working directory?

*         The View menu has ‘Show on amp;single screen’ and alternately ‘Show on amp;multiple screens’ at the bottom. I think this was intended to make the first character ‘S’ and ‘M’ a hot key.

*         I gave up scanning AD for hosts (in two domains) and found it quicker to just scan my registry

*         Renaming the Discovered Connections doesn’t seem to work.

*         I can’t find it now, but there was a menu which listed a bunch of .cpl apps. I thought it was in Terminals. If so, these should be replaced with the Display Name. Though I may have been in another app while testing Terminals.

**Comment by CarlKnox** [comment]
The cpl apps described in the prior email are in Terminals. Special Commands | Control Panel…

Some are obvious, bt=Bluetooth, powercfg, timedate, etc. Others will become known by running them, wscui, ncpa, sysdm…

 



 

 

Additionally, there is a toolbar button which isn’t descriptive and doesn’t appear to do anything. It’s the one which looks like a recycle icon, toolStripButtun4. Perhaps there’s something I don’t have installed, external to Terminals, which this opens.



 

 

From: Carl Knox [mailto:cknox64@gmail.com] 
Sent: Tuesday, December 01, 2015 8:01 AM
To: 'OliverKohlDSc/Terminals' <reply@reply.github.com>; 'OliverKohlDSc/Terminals' <Terminals@noreply.github.com>
Subject: RE: [Terminals] Terminals installer (#3)

 

I was able to install yesterday afternoon and gave it a brief trial which seems to work.

 

There are a couple of quirky things to report.

*         I was running Rob Chartier’s Terminals prior and exported the favorites. This version does not import that file. Can I, perhaps, just copy those XML files into the working directory?

*         The View menu has ‘Show on amp;single screen’ and alternately ‘Show on amp;multiple screens’ at the bottom. I think this was intended to make the first character ‘S’ and ‘M’ a hot key.

*         I gave up scanning AD for hosts (in two domains) and found it quicker to just scan my registry

*         Renaming the Discovered Connections doesn’t seem to work.

*         I can’t find it now, but there was a menu which listed a bunch of .cpl apps. I thought it was in Terminals. If so, these should be replaced with the Display Name. Though I may have been in another app while testing Terminals.

**Comment by CarlKnox** [comment]
I created a favorite using the Terminal protocol. I can connect to this host, but cannot disconnect using the toolbar icon or X in the upper right corner. I’m prompted and click Yes, but the connection doesn’t close.

 



 

In fact, I can’t close Terminals and have to use TaskMan to end the process.

 

I tried Open in New Window, which allows me to close the window, but it doesn’t communicate. I’ll investigate to ensue my host is still up.

 

 

 

From: Carl Knox [mailto:cknox64@gmail.com] 
Sent: Tuesday, December 01, 2015 8:21 AM
To: 'OliverKohlDSc/Terminals' <reply@reply.github.com>; 'OliverKohlDSc/Terminals' <Terminals@noreply.github.com>
Subject: RE: [Terminals] Terminals installer (#3)

 

The cpl apps described in the prior email are in Terminals. Special Commands | Control Panel…

Some are obvious, bt=Bluetooth, powercfg, timedate, etc. Others will become known by running them, wscui, ncpa, sysdm…

 



 

 

Additionally, there is a toolbar button which isn’t descriptive and doesn’t appear to do anything. It’s the one which looks like a recycle icon, toolStripButtun4. Perhaps there’s something I don’t have installed, external to Terminals, which this opens.



 

 

From: Carl Knox [mailto:cknox64@gmail.com] 
Sent: Tuesday, December 01, 2015 8:01 AM
To: 'OliverKohlDSc/Terminals' <reply@reply.github.com>; 'OliverKohlDSc/Terminals' <Terminals@noreply.github.com <mailto:Terminals@noreply.github.com> >
Subject: RE: [Terminals] Terminals installer (#3)

 

I was able to install yesterday afternoon and gave it a brief trial which seems to work.

 

There are a couple of quirky things to report.

*         I was running Rob Chartier’s Terminals prior and exported the favorites. This version does not import that file. Can I, perhaps, just copy those XML files into the working directory?

*         The View menu has ‘Show on amp;single screen’ and alternately ‘Show on amp;multiple screens’ at the bottom. I think this was intended to make the first character ‘S’ and ‘M’ a hot key.

*         I gave up scanning AD for hosts (in two domains) and found it quicker to just scan my registry

*         Renaming the Discovered Connections doesn’t seem to work.

*         I can’t find it now, but there was a menu which listed a bunch of .cpl apps. I thought it was in Terminals. If so, these should be replaced with the Display Name. Though I may have been in another app while testing Terminals.

**Comment by CarlKnox** [comment]
Here is additional feedback

 

Options | Startup & Shutdown | Allow a single instance of the application

-          Prompts me for the password each time and opens multiple instances

Option | Background Image | Select

-          Lets me browse and select a file. 

-          The file is copied to the Terminals folder, instead of referencing where the image is

-          The path always sets to ..\Terminals. To change the background, I need to manually add the filename to the end of ..\Terminals

**Comment by OliverKohlDSc** [comment]
Thanks a lot for all the detailed tests! I'll have a look at all these 
issues in the coming week.


Oliver Kohl D.Sc.

Herzfeldergasse 30
2351 Wiener Neudorf
Österreich



Homepage: http://www.kohl.bz

**Comment by OliverKohlDSc** [comment]
@CarlKnox 
I've now created a new issue for your report: https://github.com/OliverKohlDSc/Terminals/issues/6
The problems will be fixed in the next coming version.
Thanks Oliver

**Comment by CarlKnox** [comment]
Thank you. I look forward to trying it when ready.

**Comment by CarlKnox** [comment]
Hey, Oliver…

 

I had installed the latest version. Thanks

 

However, I keep getting a TerminalsNews tab which opens each time I launch. I also keep getting a popup that a new build is available. I even clicked OK to install, yet still get these. Any ideas?

 

 



 

 

From: Carl Knox [mailto:cknox64@gmail.com] 
Sent: Monday, February 08, 2016 11:02 AM
To: 'OliverKohlDSc/Terminals' <reply@reply.github.com>; 'OliverKohlDSc/Terminals' <Terminals@noreply.github.com>
Subject: RE: [Terminals] Terminals installer (#3)

 

Thank you. I look forward to trying it when ready.
