### ISSUE TITLE
Terminals - Network Tools / BUG

### ISSUE THREAD

**Issue by giu386** [OliverKohlDSc/Terminals#4]
INFO  2015-12-02 23:06:09,676    51ms config                 Info               - -------------------------------Terminals started. Version: 4.7.4.0, Date: 30.11.2015 14:55:26-------------------------------
WARN  2015-12-02 23:06:09,709    84ms config                 eDefaultConfigFile - Using a new plain Terminals configuration file.
INFO  2015-12-02 23:06:09,737   112ms config                 teConfigFileBackup - Configuration file backup has been created successfully.
INFO  2015-12-02 23:06:14,431  4806ms config                 SaveHistory        - History saved. Duration:12 ms
INFO  2015-12-02 23:06:14,432  4807ms config                 LoadHistory        - Load History Duration: 14 ms
WARN  2015-12-02 23:06:14,461  4836ms config                 Create             - The connection to the terminals database will be ignored.
INFO  2015-12-02 23:06:14,473  4848ms config                 GroupByDate        - Grouping history items by date.
INFO  2015-12-02 23:06:14,657  5032ms config                 ralProperties>b__0 - Command line arguments: -
INFO  2015-12-02 23:06:14,657  5032ms config                 ralProperties>b__0 - Current directory: C:\Users\Name.LastName\Desktop\Terminals_4.7.4.0
INFO  2015-12-02 23:06:14,657  5032ms config                 ralProperties>b__0 - Machine name: COMPUTER
INFO  2015-12-02 23:06:14,657  5032ms config                 ralProperties>b__0 - Machine domain: -
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - User name: -
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - User name alias: Name.LastName
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - User SID: S-1-5-21-1140432084-2390567899-3223830150-1001
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - User domain: COMPUTER
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - Registered owner: Name.LastName
INFO  2015-12-02 23:06:14,658  5033ms config                 ralProperties>b__0 - Company name: -
INFO  2015-12-02 23:06:14,659  5034ms config                 Info               - Is 64 bit OS: False
INFO  2015-12-02 23:06:14,659  5034ms config                 Info               - Is 64 bit process: False
INFO  2015-12-02 23:06:14,659  5034ms config                 Info               - Your Operating system: Windows 8 Enterprise
INFO  2015-12-02 23:06:14,659  5034ms config                 Info               - Number of processors: 4
INFO  2015-12-02 23:06:14,660  5035ms config                 Info               - User interactive: True
INFO  2015-12-02 23:06:14,660  5035ms config                 Info               - Version: 4.0.30319.34209
INFO  2015-12-02 23:06:14,660  5035ms config                 Info               - Working set: 90 MB
INFO  2015-12-02 23:06:16,966  7340ms config                 ResolveAssembly    - Dynamically resolved assembly 'CodeEditor, Version=2.9.0.2, Culture=neutral, PublicKeyToken=null'.
INFO  2015-12-02 23:06:16,976  7350ms config                 ResolveAssembly    - Dynamically resolved assembly 'ScintillaNET, Version=2.5.2.0, Culture=neutral, PublicKeyToken=948d6c9751444115'.
INFO  2015-12-02 23:06:20,395 10770ms config                 NewDocument        - New file has been loaded.
INFO  2015-12-02 23:06:20,403 10778ms config                 ResolveAssembly    - Dynamically resolved assembly 'Kohl.TinyMce, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
ERROR 2015-12-02 23:06:32,293 22667ms config                 penNetworkingTools - Open networking tools failure
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em ZedGraph.ZedGraph.Localization.Translate(String id)
   em ZedGraph.ZedGraphControl..ctor()
   em Terminals.Network.Ping.Ping.InitializeComponent()
   em Terminals.Network.Ping.Ping..ctor()
   em Terminals.Connections.TabbedTools.InitializeComponent()
   em Terminals.Connections.TabbedTools..ctor()
   em Terminals.Connections.NetworkingToolsLayout.InitializeComponent()
   em Terminals.Connections.NetworkingToolsLayout..ctor()
   em Terminals.Connections.NetworkingToolsConnection.InitializeComponent()
   em Terminals.Connections.NetworkingToolsConnection..ctor()
   em Terminals.MainForm.OpenNetworkingTools(String action, String host)

**Comment by OliverKohlDSc** [comment]
@giu386: The issue has been fixed. Please be so kind to download the latest release [as a ZIP file](https://github.com/OliverKohlDSc/Terminals/releases/download/4.7.5.0/Binaries_4.7.5.0.zip) or in form of an [installer](https://github.com/OliverKohlDSc/Terminals/releases/download/4.7.5.0/Setup_4.7.5.0.exe).
