### ISSUE TITLE
Avira blocked Terminsal 

### ISSUE THREAD

**Issue by OptimusOS** [OliverKohlDSc/Terminals#8]
By starting the terminals execution, blocked Avira with " HEUR/APC "  and Reason:

" A generic detection routine designed to detect common family characteristics shared in several variants. This special detection routine was developed in order to detect unknown variants and will be enhanced continuously."

**Comment by OliverKohlDSc** [comment]
Dear @OptimusOS 

Thanks for reporting this issue and sorry for the long delay.
It will work for you with the latest release of Terminals.

https://github.com/OliverKohlDSc/Terminals/releases/download/4.9.1.0/Terminals.zip
https://github.com/OliverKohlDSc/Terminals/releases/download/4.9.1.0/Setup_Terminals.exe

Thanks
Oliver
