### ISSUE TITLE
Importing connections from Terminals 3.6.1

### ISSUE THREAD

**Issue by curpin** [OliverKohlDSc/Terminals#9]
Hi

I am using the version of Terminals 3.6.1 from Codeplex.  I have exported the connections and I am trying to import them to this version 4.9.0.0 but nothing happens.
Is there a way to make it work? thanks

**Comment by OliverKohlDSc** [comment]
Hi,

at the moment it is not working, but I'll implement or fix the import in about two weeks. I let you know.

Best regards

Oliver

This message has been sent from my iPhone, so please be so kind to ignore possible typographical errors.

**Comment by reedcrif** [comment]
Hi, I'm using the version of Terminals 3.6.1 too and the import still not here :)

There also a missing option, I can not select a key for the ssh connection ...

Any update? Thnak you :)

**Comment by OliverKohlDSc** [comment]
Dear @reedcrif 

I'm working heavily on the new release this week. This is the next task planned to be fixed.

Thanks for your patience and thanks for using the software.

Br
Oliver

**Comment by OliverKohlDSc** [comment]
@reedcrif: Is it possible that you provide me your Terminals.config file?

**Comment by curpin** [comment]
Hi Oliver

Please find it attached.
I had to change some values as they are confidential.
Thank you for your support.  Please do not publish the file.

Toni

**Comment by OliverKohlDSc** [comment]
Dear Toni,
I haven't received your config. Seems that the mail got analysed by GitHub and the attachment seems to have been thrown away. My personal email is: oliver@kohl.bz
Thanks
Oliver

**Comment by OliverKohlDSc** [comment]
Dear @curpin @reedcrif 
Does the import work for you as described in the [wiki page](https://github.com/OliverKohlDSc/Terminals/wiki/Import-your-favorites-from-%22CodePlex-Terminals-3.6.1%22) with the [latest release](https://github.com/OliverKohlDSc/Terminals/archive/4.9.1.0.zip)?
Thanks
Oliver

**Comment by reedcrif** [comment]
Hi Oliver,

Import works if I select "Codeplex Terminals favorties" :)

I have all the connection imported but not the tree structure. I need to test more but good job :)

Ssh seems to no working.

**Comment by OliverKohlDSc** [comment]
Hi @reedcrif,

thanks for testing. I'll fix the typo in the meanwhile and I'll open a new bug for the SSH issue.

Thanks

Oliver
